### Cadastrar Pessoa
POST https://localhost:5001/crudmusic/music/create
Content-Type: application/json

{
"Nome" : "Self Esteem",
"AnoLancamento" : 1693,
"Artista" : "OffSpring",
"EstiloMusical": "Punk-Rock"

}


### Listar Pets

GET https://localhost:5001/petshop/pet/list

### Buscar Pet pelo ID

GET https://localhost:5001/petshop/pet/getbyid/3

### Alterar Pet
PUT https://localhost:5001/petshop/pet/update
Content-Type: application/json

{
"PetId" : 1,
"Nome" : "iiio update",
"Dono" : "Jose",
"TipoAnimal" : "Gato"
}

### Deletar Pet
 
DELETE https://localhost:5001/petshop/pet/delete/Tigre